// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QC5lpptsvw0u1pXccvP0FQUf2t0IlP0',
    appId: '1:174352279708:web:342e423acf7caa503ee559',
    messagingSenderId: '174352279708',
    projectId: 'quoteapplication101',
    authDomain: 'quoteapplication101.firebaseapp.com',
    storageBucket: 'quoteapplication101.firebasestorage.app',
    measurementId: 'G-XQBHJ0JX4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABe4w3EN3GDk3SqWIASiNDAIh15p9NyKE',
    appId: '1:174352279708:android:fddcc0b40e1a3ec43ee559',
    messagingSenderId: '174352279708',
    projectId: 'quoteapplication101',
    storageBucket: 'quoteapplication101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Zeik607HP0eN40_KMrtNZY1ONgRSDaA',
    appId: '1:174352279708:ios:acaedae7f46e8ef13ee559',
    messagingSenderId: '174352279708',
    projectId: 'quoteapplication101',
    storageBucket: 'quoteapplication101.firebasestorage.app',
    iosBundleId: 'com.example.quoteApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Zeik607HP0eN40_KMrtNZY1ONgRSDaA',
    appId: '1:174352279708:ios:acaedae7f46e8ef13ee559',
    messagingSenderId: '174352279708',
    projectId: 'quoteapplication101',
    storageBucket: 'quoteapplication101.firebasestorage.app',
    iosBundleId: 'com.example.quoteApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-QC5lpptsvw0u1pXccvP0FQUf2t0IlP0',
    appId: '1:174352279708:web:0edb99b1167fa69c3ee559',
    messagingSenderId: '174352279708',
    projectId: 'quoteapplication101',
    authDomain: 'quoteapplication101.firebaseapp.com',
    storageBucket: 'quoteapplication101.firebasestorage.app',
    measurementId: 'G-VQPEXDQV75',
  );
}
